### ISSUE TITLE
How to train Facenet and Mtcnn models

### ISSUE THREAD

**Issue by Ram-Godavarthi** [shubhamtyagii/facenet-mtcnn-tensorflow#1]
Hi,

I have gone through you repo. You have provided the Mtcnn and facenet models.

How did you train them ?? I could not find anything related to that.

Could you provide me the source / instructions on how to train them ??
Thank you

**Comment by shubhamtyagii** [comment]
Hi, You can use following repos to train MTCNN and Facenet respectively:

1. MTCNN: [https://github.com/AITTSMD/MTCNN-Tensorflow](url)
2. FACENET: [https://github.com/davidsandberg/facenet](url)
